import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_content_columns_custom_heading_level" AS ENUM('all', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_custom_heading_level" AS ENUM('all', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  CREATE TYPE "public"."enum_magazines_blocks_content_columns_custom_heading_level" AS ENUM('all', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  CREATE TYPE "public"."enum__magazines_v_blocks_content_columns_custom_heading_level" AS ENUM('all', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  CREATE TYPE "public"."enum_footer_blocks_content_columns_custom_heading_level" AS ENUM('all', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  ALTER TYPE "public"."enum_pages_blocks_content_columns_links_link_appearance" ADD VALUE 'themeAware';
  ALTER TYPE "public"."enum_pages_blocks_content_columns_link_appearance" ADD VALUE 'themeAware';
  ALTER TYPE "public"."enum_pages_hero_links_link_appearance" ADD VALUE 'themeAware';
  ALTER TYPE "public"."enum__pages_v_blocks_content_columns_links_link_appearance" ADD VALUE 'themeAware';
  ALTER TYPE "public"."enum__pages_v_blocks_content_columns_link_appearance" ADD VALUE 'themeAware';
  ALTER TYPE "public"."enum__pages_v_version_hero_links_link_appearance" ADD VALUE 'themeAware';
  ALTER TYPE "public"."enum_magazines_blocks_content_columns_links_link_appearance" ADD VALUE 'themeAware';
  ALTER TYPE "public"."enum_magazines_blocks_content_columns_link_appearance" ADD VALUE 'themeAware';
  ALTER TYPE "public"."enum_magazines_hero_links_link_appearance" ADD VALUE 'themeAware';
  ALTER TYPE "public"."enum__magazines_v_blocks_content_columns_links_link_appearance" ADD VALUE 'themeAware';
  ALTER TYPE "public"."enum__magazines_v_blocks_content_columns_link_appearance" ADD VALUE 'themeAware';
  ALTER TYPE "public"."enum__magazines_v_version_hero_links_link_appearance" ADD VALUE 'themeAware';
  ALTER TYPE "public"."enum_footer_blocks_content_columns_links_link_appearance" ADD VALUE 'themeAware';
  ALTER TYPE "public"."enum_footer_blocks_content_columns_link_appearance" ADD VALUE 'themeAware';
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "custom_heading_size" numeric;
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "custom_heading_level" "enum_pages_blocks_content_columns_custom_heading_level" DEFAULT 'h3';
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "custom_heading_size" numeric;
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "custom_heading_level" "enum__pages_v_blocks_content_columns_custom_heading_level" DEFAULT 'h3';
  ALTER TABLE "posts" ADD COLUMN "views" numeric DEFAULT 0;
  ALTER TABLE "_posts_v" ADD COLUMN "version_views" numeric DEFAULT 0;
  ALTER TABLE "magazines_blocks_content_columns" ADD COLUMN "custom_heading_size" numeric;
  ALTER TABLE "magazines_blocks_content_columns" ADD COLUMN "custom_heading_level" "enum_magazines_blocks_content_columns_custom_heading_level" DEFAULT 'h3';
  ALTER TABLE "_magazines_v_blocks_content_columns" ADD COLUMN "custom_heading_size" numeric;
  ALTER TABLE "_magazines_v_blocks_content_columns" ADD COLUMN "custom_heading_level" "enum__magazines_v_blocks_content_columns_custom_heading_level" DEFAULT 'h3';
  ALTER TABLE "footer_blocks_content_columns" ADD COLUMN "custom_heading_size" numeric;
  ALTER TABLE "footer_blocks_content_columns" ADD COLUMN "custom_heading_level" "enum_footer_blocks_content_columns_custom_heading_level" DEFAULT 'h3';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum_pages_blocks_content_columns_links_link_appearance";
  CREATE TYPE "public"."enum_pages_blocks_content_columns_links_link_appearance" AS ENUM('default', 'outline');
  ALTER TABLE "pages_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::"public"."enum_pages_blocks_content_columns_links_link_appearance";
  ALTER TABLE "pages_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DATA TYPE "public"."enum_pages_blocks_content_columns_links_link_appearance" USING "link_appearance"::"public"."enum_pages_blocks_content_columns_links_link_appearance";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_appearance" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum_pages_blocks_content_columns_link_appearance";
  CREATE TYPE "public"."enum_pages_blocks_content_columns_link_appearance" AS ENUM('default', 'outline');
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::"public"."enum_pages_blocks_content_columns_link_appearance";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_appearance" SET DATA TYPE "public"."enum_pages_blocks_content_columns_link_appearance" USING "link_appearance"::"public"."enum_pages_blocks_content_columns_link_appearance";
  ALTER TABLE "pages_hero_links" ALTER COLUMN "link_appearance" SET DATA TYPE text;
  ALTER TABLE "pages_hero_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum_pages_hero_links_link_appearance";
  CREATE TYPE "public"."enum_pages_hero_links_link_appearance" AS ENUM('default', 'outline');
  ALTER TABLE "pages_hero_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::"public"."enum_pages_hero_links_link_appearance";
  ALTER TABLE "pages_hero_links" ALTER COLUMN "link_appearance" SET DATA TYPE "public"."enum_pages_hero_links_link_appearance" USING "link_appearance"::"public"."enum_pages_hero_links_link_appearance";
  ALTER TABLE "_pages_v_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_links_link_appearance";
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_links_link_appearance" AS ENUM('default', 'outline');
  ALTER TABLE "_pages_v_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::"public"."enum__pages_v_blocks_content_columns_links_link_appearance";
  ALTER TABLE "_pages_v_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DATA TYPE "public"."enum__pages_v_blocks_content_columns_links_link_appearance" USING "link_appearance"::"public"."enum__pages_v_blocks_content_columns_links_link_appearance";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_appearance" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_link_appearance";
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_link_appearance" AS ENUM('default', 'outline');
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::"public"."enum__pages_v_blocks_content_columns_link_appearance";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_appearance" SET DATA TYPE "public"."enum__pages_v_blocks_content_columns_link_appearance" USING "link_appearance"::"public"."enum__pages_v_blocks_content_columns_link_appearance";
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_appearance" SET DATA TYPE text;
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum__pages_v_version_hero_links_link_appearance";
  CREATE TYPE "public"."enum__pages_v_version_hero_links_link_appearance" AS ENUM('default', 'outline');
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::"public"."enum__pages_v_version_hero_links_link_appearance";
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_appearance" SET DATA TYPE "public"."enum__pages_v_version_hero_links_link_appearance" USING "link_appearance"::"public"."enum__pages_v_version_hero_links_link_appearance";
  ALTER TABLE "magazines_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DATA TYPE text;
  ALTER TABLE "magazines_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum_magazines_blocks_content_columns_links_link_appearance";
  CREATE TYPE "public"."enum_magazines_blocks_content_columns_links_link_appearance" AS ENUM('default', 'outline');
  ALTER TABLE "magazines_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::"public"."enum_magazines_blocks_content_columns_links_link_appearance";
  ALTER TABLE "magazines_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DATA TYPE "public"."enum_magazines_blocks_content_columns_links_link_appearance" USING "link_appearance"::"public"."enum_magazines_blocks_content_columns_links_link_appearance";
  ALTER TABLE "magazines_blocks_content_columns" ALTER COLUMN "link_appearance" SET DATA TYPE text;
  ALTER TABLE "magazines_blocks_content_columns" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum_magazines_blocks_content_columns_link_appearance";
  CREATE TYPE "public"."enum_magazines_blocks_content_columns_link_appearance" AS ENUM('default', 'outline');
  ALTER TABLE "magazines_blocks_content_columns" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::"public"."enum_magazines_blocks_content_columns_link_appearance";
  ALTER TABLE "magazines_blocks_content_columns" ALTER COLUMN "link_appearance" SET DATA TYPE "public"."enum_magazines_blocks_content_columns_link_appearance" USING "link_appearance"::"public"."enum_magazines_blocks_content_columns_link_appearance";
  ALTER TABLE "magazines_hero_links" ALTER COLUMN "link_appearance" SET DATA TYPE text;
  ALTER TABLE "magazines_hero_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum_magazines_hero_links_link_appearance";
  CREATE TYPE "public"."enum_magazines_hero_links_link_appearance" AS ENUM('default', 'outline');
  ALTER TABLE "magazines_hero_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::"public"."enum_magazines_hero_links_link_appearance";
  ALTER TABLE "magazines_hero_links" ALTER COLUMN "link_appearance" SET DATA TYPE "public"."enum_magazines_hero_links_link_appearance" USING "link_appearance"::"public"."enum_magazines_hero_links_link_appearance";
  ALTER TABLE "_magazines_v_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DATA TYPE text;
  ALTER TABLE "_magazines_v_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum__magazines_v_blocks_content_columns_links_link_appearance";
  CREATE TYPE "public"."enum__magazines_v_blocks_content_columns_links_link_appearance" AS ENUM('default', 'outline');
  ALTER TABLE "_magazines_v_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::"public"."enum__magazines_v_blocks_content_columns_links_link_appearance";
  ALTER TABLE "_magazines_v_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DATA TYPE "public"."enum__magazines_v_blocks_content_columns_links_link_appearance" USING "link_appearance"::"public"."enum__magazines_v_blocks_content_columns_links_link_appearance";
  ALTER TABLE "_magazines_v_blocks_content_columns" ALTER COLUMN "link_appearance" SET DATA TYPE text;
  ALTER TABLE "_magazines_v_blocks_content_columns" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum__magazines_v_blocks_content_columns_link_appearance";
  CREATE TYPE "public"."enum__magazines_v_blocks_content_columns_link_appearance" AS ENUM('default', 'outline');
  ALTER TABLE "_magazines_v_blocks_content_columns" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::"public"."enum__magazines_v_blocks_content_columns_link_appearance";
  ALTER TABLE "_magazines_v_blocks_content_columns" ALTER COLUMN "link_appearance" SET DATA TYPE "public"."enum__magazines_v_blocks_content_columns_link_appearance" USING "link_appearance"::"public"."enum__magazines_v_blocks_content_columns_link_appearance";
  ALTER TABLE "_magazines_v_version_hero_links" ALTER COLUMN "link_appearance" SET DATA TYPE text;
  ALTER TABLE "_magazines_v_version_hero_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum__magazines_v_version_hero_links_link_appearance";
  CREATE TYPE "public"."enum__magazines_v_version_hero_links_link_appearance" AS ENUM('default', 'outline');
  ALTER TABLE "_magazines_v_version_hero_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::"public"."enum__magazines_v_version_hero_links_link_appearance";
  ALTER TABLE "_magazines_v_version_hero_links" ALTER COLUMN "link_appearance" SET DATA TYPE "public"."enum__magazines_v_version_hero_links_link_appearance" USING "link_appearance"::"public"."enum__magazines_v_version_hero_links_link_appearance";
  ALTER TABLE "footer_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DATA TYPE text;
  ALTER TABLE "footer_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum_footer_blocks_content_columns_links_link_appearance";
  CREATE TYPE "public"."enum_footer_blocks_content_columns_links_link_appearance" AS ENUM('default', 'outline');
  ALTER TABLE "footer_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::"public"."enum_footer_blocks_content_columns_links_link_appearance";
  ALTER TABLE "footer_blocks_content_columns_links" ALTER COLUMN "link_appearance" SET DATA TYPE "public"."enum_footer_blocks_content_columns_links_link_appearance" USING "link_appearance"::"public"."enum_footer_blocks_content_columns_links_link_appearance";
  ALTER TABLE "footer_blocks_content_columns" ALTER COLUMN "link_appearance" SET DATA TYPE text;
  ALTER TABLE "footer_blocks_content_columns" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum_footer_blocks_content_columns_link_appearance";
  CREATE TYPE "public"."enum_footer_blocks_content_columns_link_appearance" AS ENUM('default', 'outline');
  ALTER TABLE "footer_blocks_content_columns" ALTER COLUMN "link_appearance" SET DEFAULT 'default'::"public"."enum_footer_blocks_content_columns_link_appearance";
  ALTER TABLE "footer_blocks_content_columns" ALTER COLUMN "link_appearance" SET DATA TYPE "public"."enum_footer_blocks_content_columns_link_appearance" USING "link_appearance"::"public"."enum_footer_blocks_content_columns_link_appearance";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "custom_heading_size";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "custom_heading_level";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "custom_heading_size";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "custom_heading_level";
  ALTER TABLE "posts" DROP COLUMN "views";
  ALTER TABLE "_posts_v" DROP COLUMN "version_views";
  ALTER TABLE "magazines_blocks_content_columns" DROP COLUMN "custom_heading_size";
  ALTER TABLE "magazines_blocks_content_columns" DROP COLUMN "custom_heading_level";
  ALTER TABLE "_magazines_v_blocks_content_columns" DROP COLUMN "custom_heading_size";
  ALTER TABLE "_magazines_v_blocks_content_columns" DROP COLUMN "custom_heading_level";
  ALTER TABLE "footer_blocks_content_columns" DROP COLUMN "custom_heading_size";
  ALTER TABLE "footer_blocks_content_columns" DROP COLUMN "custom_heading_level";
  DROP TYPE "public"."enum_pages_blocks_content_columns_custom_heading_level";
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_custom_heading_level";
  DROP TYPE "public"."enum_magazines_blocks_content_columns_custom_heading_level";
  DROP TYPE "public"."enum__magazines_v_blocks_content_columns_custom_heading_level";
  DROP TYPE "public"."enum_footer_blocks_content_columns_custom_heading_level";`)
}
